"""change password to sha256

Revision ID: 0679722b5fb3
Revises: 0687249689cb
Create Date: 2026-05-11 22:53:49.014471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0679722b5fb3'
down_revision: Union[str, Sequence[str], None] = '0687249689cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###
