"""expand password column to 255

Revision ID: 8454534d779e
Revises: 0679722b5fb3
Create Date: 2026-05-14 14:47:58.780689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8454534d779e'
down_revision: Union[str, Sequence[str], None] = '0679722b5fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'account_name',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('user_account', 'account_name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###
